(() => {
  "use strict";
  const KEYS={plans:"bp_session_plans",locks:"bp_rulebook_locks",templates:"bp_market_templates",timeline:"bp_screenshot_timeline",weekly:"bp_weekly_ai_reviews",partner:"bp_accountability_partner"};
  const $=selector=>document.querySelector(selector);const $$=selector=>Array.from(document.querySelectorAll(selector));
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  const write=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));setTimeout(()=>window.BullProsperity?.sync?.(),60);};
  const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const trades=()=>{const value=read("bullprosperity_trading_journal",[]);return Array.isArray(value)?value:[]};
  const pretradePlans=()=>read("bp_pretrade_plans",[]);const reviews=()=>read("bp_process_reviews",[]);const completedLessons=()=>Object.keys(read("bp_completed_lessons",{})).filter(key=>read("bp_completed_lessons",{})[key]);
  const sameDay=value=>String(value||"").slice(0,10)===today();

  function setupSessionPlanner(){const saved=read(KEYS.plans,{})[today()];if(saved)fillPlan(saved);$("#sessionPlannerForm").addEventListener("submit",event=>{event.preventDefault();if(shieldState().limitReached)return renderShield();const all=read(KEYS.plans,{});all[today()]={market:$("#sessionMarket").value.trim(),session:$("#sessionWindow").value,bias:$("#sessionBias").value,risk:Number($("#sessionRisk").value),news:$("#sessionNews").value,newsEvent:$("#sessionNewsEvent").value.trim(),focus:$("#sessionFocus").value.trim(),updatedAt:new Date().toISOString()};write(KEYS.plans,all);renderAll();});$("#saveMarketTemplate").addEventListener("click",saveTemplate);renderSessionPlan();}
  function fillPlan(plan){$("#sessionMarket").value=plan.market||"";$("#sessionWindow").value=plan.session||"London";$("#sessionBias").value=plan.bias||"Neutral";$("#sessionRisk").value=plan.risk||1;$("#sessionNews").value=plan.news||"Keine High-Impact-News";$("#sessionNewsEvent").value=plan.newsEvent||"";$("#sessionFocus").value=plan.focus||"";}
  function renderSessionPlan(){const plan=read(KEYS.plans,{})[today()];const box=$("#sessionPlanStatus");if(!plan){box.className="status-box";box.textContent="Noch kein Tagesplan gespeichert.";return;}const newsDetail=plan.newsEvent?`${plan.news}: ${plan.newsEvent}`:plan.news||"News nicht dokumentiert";box.className="status-box good";box.textContent=`${plan.market} · ${plan.session} · ${plan.bias} · max. ${plan.risk}% · ${newsDetail} · ${plan.focus}`;}

  function calculateStreak(){const daily=read("bp_daily_os",{});let cursor=new Date();const current=daily[today()];if(!(current?.prepare&&current?.execute&&current?.review))cursor.setDate(cursor.getDate()-1);let count=0;for(let i=0;i<365;i++){const key=cursor.toISOString().slice(0,10),day=daily[key];if(!(day?.prepare&&day?.execute&&day?.review))break;count++;cursor.setDate(cursor.getDate()-1);}return count;}
  function renderStreak(){const count=calculateStreak();$("#processStreak").textContent=count;$("#streakProgress").style.setProperty("--progress",`${Math.min(100,count/7*100)}%`);$("#streakStatus").textContent=count>=7?"Sieben-Tage-Prozess erreicht. Qualität stabil halten.":`${Math.max(0,7-count)} saubere Tage bis zum nächsten Prozess-Meilenstein.`;}

  function mistakeData(){const list=trades(),reviewList=reviews();return[{title:"Stop Loss fehlt",count:list.filter(item=>!item.stopLoss).length,detail:"Journal-Einträge ohne dokumentierte Invalidation"},{title:"Emotionaler Trigger",count:list.filter(item=>/fomo|stress|ungeduldig|emotional|angst/i.test(item.emotion||"")).length,detail:"FOMO, Stress oder Ungeduld dokumentiert"},{title:"Learning fehlt",count:list.filter(item=>(item.result==="Verlust"||Number(item.profitLoss)<0)&&!String(item.notes||"").trim()).length,detail:"Verluste ohne nachträgliche Reflexion"},{title:"Regeltreue niedrig",count:reviewList.filter(item=>Number(item.adherence)<70).length,detail:"Reviews unter 70 % Regelkonformität"}].sort((a,b)=>b.count-a.count);}
  function renderMistakes(){$("#mistakePatterns").innerHTML=mistakeData().map(item=>`<article class="pattern-item"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span><b>${item.count}</b></article>`).join("");}

  function lockChecks(){const plan=read(KEYS.plans,{})[today()],daily=read("bp_daily_os",{})[today()]||{},rulebook=localStorage.getItem("bp_personal_rulebook")||"",risk=read("bp_risk_profile",{dailyRisk:2});return[{key:"rulebook",label:"Persönliches Rulebook hinterlegt",ok:rulebook.trim().length>=20},{key:"plan",label:"Tagesplan gespeichert",ok:Boolean(plan)},{key:"prepare",label:"Prepare-Routine abgeschlossen",ok:Boolean(daily.prepare)},{key:"risk",label:"Tagesrisiko im eigenen Limit",ok:Boolean(plan)&&Number(plan.risk)<=Number(risk.dailyRisk||2)}];}
  function setupRulebookLock(){$("#activateRulebookLock").addEventListener("click",()=>{const checks=lockChecks();if(checks.some(item=>!item.ok))return renderRulebookLock();const all=read(KEYS.locks,{}),rulebook=localStorage.getItem("bp_personal_rulebook")||"";all[today()]={lockedAt:new Date().toISOString(),fingerprint:[...rulebook].reduce((sum,char)=>(sum*31+char.charCodeAt(0))>>>0,7)};write(KEYS.locks,all);renderAll();});$("#personalRulebook")?.addEventListener("input",()=>setTimeout(renderAll,80));renderRulebookLock();}
  function renderRulebookLock(){const checks=lockChecks(),lock=read(KEYS.locks,{})[today()];$("#lockRequirements").innerHTML=checks.map(item=>`<div class="check-item"><span><strong>${item.ok?"Erledigt":"Offen"}</strong><br>${escapeHtml(item.label)}</span></div>`).join("");$("#activateRulebookLock").disabled=checks.some(item=>!item.ok)||Boolean(lock);$("#rulebookLockStatus").className=`status-box ${lock?"good":checks.some(item=>!item.ok)?"alert":""}`;$("#rulebookLockStatus").textContent=lock?`Fixiert um ${new Date(lock.lockedAt).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}. Änderungen gelten erst für den nächsten Tagesprozess.`:checks.some(item=>!item.ok)?"Schließe zuerst alle vier Voraussetzungen ab.":"Bereit zum Fixieren.";}

  function shieldState(){const lock=Boolean(read(KEYS.locks,{})[today()]),profile=read("bp_risk_profile",{dailyRisk:2,maxTrades:3}),plan=read(KEYS.plans,{})[today()],todayTrades=trades().filter(item=>sameDay(item.date)).length,maxTrades=Number(profile.maxTrades||3),reasons=[],limitReached=todayTrades>=maxTrades;if(!lock)reasons.push("Rulebook nicht fixiert");if(!plan)reasons.push("Tagesplan fehlt");if(plan&&Number(plan.risk)>Number(profile.dailyRisk||2))reasons.push("Risikolimit überschritten");if(limitReached)reasons.push(`Trade-Limit erreicht (${todayTrades}/${maxTrades})`);return{open:reasons.length===0,reasons,limitReached};}
  function renderShield(){const shield=shieldState(),execute=$("[data-daily='execute']");$("#shieldHeadline").textContent=shield.limitReached?"Tageslimit erreicht":shield.open?"Prozess vollständig":"Shield aktiv";$("#shieldIndicator").classList.toggle("is-open",shield.open);$("#shieldStatus").className=`status-box ${shield.open?"good":"alert"}`;$("#shieldStatus").textContent=shield.limitReached?`${shield.reasons.join(" · ")}. Neue Tages- und Pre-Trade-Pläne sind bis morgen gesperrt.`:shield.open?"Eigene Voraussetzungen erfüllt. Das ist keine Handelsfreigabe.":shield.reasons.join(" · ");if(execute&&!execute.checked)execute.disabled=!shield.open;$$('#sessionPlannerForm button[type="submit"],#gatekeeperForm button[type="submit"]').forEach(button=>{if(shield.limitReached){button.disabled=true;button.dataset.shieldBlocked="true";button.title="Tageslimit erreicht";}else if(button.dataset.shieldBlocked==="true"){button.disabled=false;delete button.dataset.shieldBlocked;button.removeAttribute("title");}});}

  function saveTemplate(){const plan={market:$("#sessionMarket").value.trim(),session:$("#sessionWindow").value,bias:$("#sessionBias").value,risk:Number($("#sessionRisk").value),news:$("#sessionNews").value,newsEvent:$("#sessionNewsEvent").value.trim()};if(!plan.market)return;const list=read(KEYS.templates,[]);list.unshift({id:uid(),name:`${plan.market} ${plan.session}`,...plan});write(KEYS.templates,list.slice(0,12));renderTemplates();}
  function renderTemplates(){const list=read(KEYS.templates,[]);$("#marketTemplateList").innerHTML=list.length?list.map(item=>`<article class="stack-item"><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.bias)} · Risiko ${Number(item.risk)}% · ${escapeHtml(item.news||"News nicht dokumentiert")}</span><div class="lab-actions"><button class="lab-btn" data-template-use="${item.id}" type="button">Anwenden</button><button class="lab-btn danger" data-template-delete="${item.id}" type="button">Löschen</button></div></article>`).join(""):'<div class="status-box">Noch keine Vorlage gespeichert.</div>';$$('[data-template-use]').forEach(button=>button.addEventListener("click",()=>{const item=read(KEYS.templates,[]).find(entry=>entry.id===button.dataset.templateUse);if(item)fillPlan(item);}));$$('[data-template-delete]').forEach(button=>button.addEventListener("click",()=>{write(KEYS.templates,read(KEYS.templates,[]).filter(item=>item.id!==button.dataset.templateDelete));renderTemplates();}));}

  function compressImage(file){return new Promise((resolve,reject)=>{if(!file||file.size>5*1024*1024)return reject(new Error("Bild darf maximal 5 MB groß sein."));const reader=new FileReader();reader.onerror=()=>reject(new Error("Bild konnte nicht gelesen werden."));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Ungültiges Bild."));image.onload=()=>{const scale=Math.min(1,640/image.width),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.5));};image.src=reader.result;};reader.readAsDataURL(file);});}
  function setupScreenshotTimeline(){$("#screenshotTimelineForm").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const before=await compressImage($("#timelineBefore").files[0]),after=await compressImage($("#timelineAfter").files[0]);const list=read(KEYS.timeline,[]);list.unshift({id:uid(),before,after,learning:$("#timelineLearning").value.trim(),createdAt:new Date().toISOString()});while(JSON.stringify(list).length>470000||list.length>3)list.pop();write(KEYS.timeline,list);event.target.reset();renderTimeline();}catch(error){alert(error.message);}finally{button.disabled=false;}});renderTimeline();}
  function renderTimeline(){const list=read(KEYS.timeline,[]);$("#screenshotTimeline").innerHTML=list.length?list.map(item=>`<article class="timeline-compare"><figure><img src="${item.before}" alt="Chart vor der Session" /><figcaption>Vorher</figcaption></figure><figure><img src="${item.after}" alt="Chart nach der Session" /><figcaption>Nachher</figcaption></figure><p>${escapeHtml(item.learning)}</p></article>`).join(""):'<div class="status-box">Noch kein Vorher-/Nachher-Vergleich gespeichert.</div>';}

  function scores(){const planList=pretradePlans(),reviewList=reviews(),list=trades();return{preparation:planList.length?Math.round(planList.filter(item=>item.approved).length/planList.length*100):0,discipline:reviewList.length?Math.round(reviewList.reduce((sum,item)=>sum+Number(item.adherence||0),0)/reviewList.length):0,journal:list.length?Math.round(list.reduce((sum,item)=>sum+[item.market,item.stopLoss,item.notes,item.emotion].filter(Boolean).length/4,0)/list.length*100):0,learning:Math.round(completedLessons().length/33*100)};}
  function setupWeeklyAi(){$("#runWeeklyAi").addEventListener("click",async()=>{const button=$("#runWeeklyAi"),output=$("#weeklyAiOutput");button.disabled=true;output.textContent="Die letzten sieben Tage werden ausgewertet …";try{const response=await fetch("/api/performance-coach",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"weekly",rulebook:localStorage.getItem("bp_personal_rulebook")||"Noch nicht hinterlegt",scores:scores(),dna:{mistakes:mistakeData()},recentReviews:reviews().slice(0,12),recentPlans:pretradePlans().slice(0,12),recentTrades:trades().slice(0,20)})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Review nicht verfügbar");output.textContent=data.coaching;const history=read(KEYS.weekly,[]);history.unshift({text:data.coaching,createdAt:new Date().toISOString()});write(KEYS.weekly,history.slice(0,12));}catch{output.textContent=localWeeklyReview();}finally{button.disabled=false;}});const latest=read(KEYS.weekly,[])[0];if(latest)$("#weeklyAiOutput").textContent=latest.text;}
  function localWeeklyReview(){const score=scores(),top=mistakeData()[0];return`Wochenreview\n\nStabilster Bereich: ${Object.entries(score).sort((a,b)=>b[1]-a[1])[0]?.[0]||"noch offen"}.\nPriorität: ${top?.count?`${top.title} (${top.count} dokumentiert)`:"Datenqualität weiter ausbauen"}.\nNächste Routine: jeden Plan mit Invalidation und anschließendem Learning schließen.\n\nKeine Marktprognose oder Anlageberatung.`;}

  function renderSetupQuality(){const plan=pretradePlans()[0];if(!plan){$("#setupQualityScore").textContent="0";$("#setupQualityStatus").textContent="Noch kein Plan vorhanden.";return;}const fields=[plan.market,plan.bias,plan.session,plan.context,plan.invalidation,Number(plan.risk)>0],fieldScore=fields.filter(Boolean).length/fields.length*60,checkScore=Number(plan.totalChecks)?Number(plan.completedChecks)/Number(plan.totalChecks)*40:0,score=Math.round(fieldScore+checkScore);$("#setupQualityScore").textContent=score;$("#setupQualityProgress").style.setProperty("--progress",`${score}%`);$("#setupQualityStatus").className=`status-box ${score>=85?"good":score<60?"alert":""}`;$("#setupQualityStatus").textContent=score>=85?"Plan vollständig dokumentiert.":"Ergänze Kontext, Invalidation oder offene Checks.";}

  function emotionCategory(value){const text=String(value||"").toLowerCase();if(/ruhig|fokus|klar|geduld/.test(text))return"Ruhig";if(/fomo|ungeduld|impuls/.test(text))return"FOMO";if(/stress|angst|nerv/.test(text))return"Stress";return"Unsicher";}
  function renderEmotionHeatmap(){const sessions=["London","New York","Asia","Swing"],emotions=["Ruhig","FOMO","Stress","Unsicher"],list=trades(),max=Math.max(1,...sessions.flatMap(session=>emotions.map(emotion=>list.filter(item=>String(item.session||"").toLowerCase()===session.toLowerCase()&&emotionCategory(item.emotion)===emotion).length)));let html='<div class="heat-cell header"></div>'+emotions.map(item=>`<div class="heat-cell header">${item}</div>`).join("");sessions.forEach(session=>{html+=`<div class="heat-cell header">${session}</div>`;emotions.forEach(emotion=>{const count=list.filter(item=>String(item.session||"").toLowerCase()===session.toLowerCase()&&emotionCategory(item.emotion)===emotion).length;html+=`<div class="heat-cell" style="--heat:${(.04+count/max*.3).toFixed(2)}"><strong>${count}</strong>${emotion}</div>`;});});$("#emotionHeatmap").innerHTML=html;}

  let replayStep=0,replayValues=[];
  function setupJournalReplay(){const select=$("#journalReplayTrade");select.addEventListener("change",()=>{replayStep=0;prepareReplay();});$("#journalReplayNext").addEventListener("click",()=>{replayStep=Math.min(replayValues.length,replayStep+1);renderReplay();});$("#journalReplayReset").addEventListener("click",()=>{replayStep=0;renderReplay();});renderJournalOptions();}
  function renderJournalOptions(){const select=$("#journalReplayTrade"),current=select.value,list=trades();select.innerHTML='<option value="">Trade auswählen</option>'+list.slice(0,40).map((item,index)=>`<option value="${index}">${escapeHtml(item.date||"")} · ${escapeHtml(item.market||"Trade")} · ${escapeHtml(item.result||"")}</option>`).join("");if(current&&Number(current)<list.length)select.value=current;prepareReplay();}
  function prepareReplay(){const index=Number($("#journalReplayTrade").value),trade=trades()[index];if(!trade||$("#journalReplayTrade").value===""){replayValues=[];renderReplay();return;}let seed=[...`${trade.market}${trade.date}${trade.result}`].reduce((sum,char)=>sum+char.charCodeAt(0),1);replayValues=Array.from({length:16},()=>{seed=(seed*9301+49297)%233280;return 28+Math.round(seed/233280*64)});$("#journalReplayBars").innerHTML=replayValues.map((height,i)=>`<span class="os-replay-bar ${i%4===1?'bear':''}" style="height:${height}%"></span>`).join("");$("#journalReplayPrompt").textContent=`Reflektiere ${trade.market||"den Trade"}: Welche Information war zu diesem Zeitpunkt wirklich verfügbar?`;renderReplay();}
  function renderReplay(){const cover=$("#journalReplayCover");if(!replayValues.length){cover.style.width="100%";cover.textContent="Trade auswählen";return;}cover.style.width=`${Math.max(0,100-replayStep/replayValues.length*100)}%`;cover.textContent=replayStep?`${replayStep}/${replayValues.length} Kerzen sichtbar`:"Nächsten Schritt aufdecken";}

  function renderLearningPath(){const mistakes=mistakeData(),done=completedLessons(),recommendations=[];if(mistakes.find(item=>item.title==="Stop Loss fehlt"&&item.count))recommendations.push([20,"Risk Management","Invalidation und Risiko vertiefen"]);if(mistakes.find(item=>item.title==="Emotionaler Trigger"&&item.count))recommendations.push([25,"Trading Psychology","Emotionale Trigger reflektieren"]);if(reviews().some(item=>Number(item.adherence)<70))recommendations.push([29,"Trade Review","Regelkonformität verbessern"]);if(!pretradePlans().length)recommendations.push([1,"Grundlagen","Strukturierten Plan beginnen"]);[[30,"Marktmodell","Kontext vertiefen"],[31,"Execution","Ausführung präzisieren"],[33,"Master Review","System zusammenführen"]].forEach(item=>{if(recommendations.length<3)recommendations.push(item)});const unique=recommendations.filter((item,index,array)=>array.findIndex(other=>other[0]===item[0])===index).slice(0,3);$("#personalLearningPath").innerHTML=unique.map((item,index)=>`<a class="learning-step" href="/lesson${item[0]}"><b>${index+1}</b><div><strong>${escapeHtml(item[1])}</strong><span>${escapeHtml(item[2])}</span></div><small>${done.includes(`lesson${item[0]}`)?"Erledigt":"Öffnen"}</small></a>`).join("");}

  function setupPartner(){const partner=read(KEYS.partner,{});$("#partnerName").value=partner.name||"";$("#partnerDiscord").value=partner.discord||"";$("#partnerGoal").value=partner.goal||"";$("#partnerForm").addEventListener("submit",event=>{event.preventDefault();write(KEYS.partner,{...read(KEYS.partner,{}),name:$("#partnerName").value.trim(),discord:$("#partnerDiscord").value.trim(),goal:$("#partnerGoal").value.trim(),updatedAt:new Date().toISOString()});renderPartner();});$("#partnerCheckin").addEventListener("click",()=>{const value=read(KEYS.partner,{});if(!value.name)return;value.checkins=value.checkins||[];const week=`${new Date().getFullYear()}-W${Math.ceil((((new Date())-new Date(new Date().getFullYear(),0,1))/86400000+new Date(new Date().getFullYear(),0,1).getDay()+1)/7)}`;if(!value.checkins.includes(week))value.checkins.push(week);write(KEYS.partner,value);renderPartner();});renderPartner();}
  function renderPartner(){const partner=read(KEYS.partner,{});$("#partnerStatus").className=`status-box ${partner.name?"good":""}`;$("#partnerStatus").textContent=partner.name?`${partner.name} · ${partner.discord} · Ziel: ${partner.goal} · ${partner.checkins?.length||0} Check-ins`:"Noch keine Partner-Vereinbarung.";}

  function renderMilestones(){const daily=read("bp_daily_os",{}),cleanDays=Object.values(daily).filter(day=>day.prepare&&day.execute&&day.review).length,certs=Object.values(read("bp_setup_certifications",{})).filter(item=>item.certified).length,items=[{name:"First Process",text:"Erster vollständiger Tagesprozess",earned:cleanDays>=1},{name:"Seven Day Standard",text:"Sieben vollständige Routinen",earned:cleanDays>=7},{name:"Journal Builder",text:"Zehn dokumentierte Trades",earned:trades().length>=10},{name:"Rulebook Locked",text:"Eigene Regeln vor der Session fixiert",earned:Boolean(read(KEYS.locks,{})[today()])},{name:"Review Discipline",text:"Zehn Reviews über 80 %",earned:reviews().filter(item=>Number(item.adherence)>=80).length>=10},{name:"Setup Mastery",text:"Ein Setup intern zertifiziert",earned:certs>=1},{name:"Learning Path",text:"Zwanzig Lessons abgeschlossen",earned:completedLessons().length>=20},{name:"Accountability",text:"Vier Partner- oder Squad-Check-ins",earned:(read(KEYS.partner,{}).checkins?.length||0)+(read("bp_squad_profile",{}).checkins?.length||0)>=4}];$("#memberMilestones").innerHTML=items.map(item=>`<article class="milestone ${item.earned?'is-earned':''}"><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.text)}</span><b>${item.earned?'Erreicht':'Noch offen'}</b></article>`).join("");}

  function renderAll(){renderSessionPlan();renderStreak();renderMistakes();renderRulebookLock();renderShield();renderTemplates();renderTimeline();renderSetupQuality();renderEmotionHeatmap();renderLearningPath();renderPartner();renderMilestones();}
  function refreshData(){renderJournalOptions();renderAll();}
  function initialize(){setupSessionPlanner();setupRulebookLock();setupScreenshotTimeline();setupWeeklyAi();setupJournalReplay();setupPartner();$$('[data-daily]').forEach(input=>input.addEventListener("change",()=>setTimeout(renderAll,80)));window.addEventListener("bp:cloud-ready",refreshData);window.addEventListener("bp:performance-updated",()=>setTimeout(refreshData,80));renderAll();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialize,{once:true});else initialize();
})();
